In [1]:
# violent crime = rape or sexual assault, robbery, aggravated and simple assault
# https://en.wikipedia.org/wiki/Violent_crime

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time

In [3]:
output_path = "csv_output/crime_cnt_df.csv"
national_output_path = "csv_output/national_crime_cnt_df.csv"
#This section is where we gather crime data

ORI_file = "csv_data/ORI.csv"

#import ORI file into a dataframe for analysis.
ORI_df = pd.read_csv(ORI_file, header=None)
ORI_df.head()

,0,1,2,3,4,5,6
0,TX1010000,HARRIS CO SO HOUSTON,SHERIFF'S OFFICE,NaN,NaN,2,HARRIS
1,TX1010100,BAYTOWN PD,BAYTOWN PD,NaN,NaN,3,HARRIS
2,TX101013A,COUNTY ATTORNEY'S OFFICE HOUSTON,COUNTY ATTORNEY'S OFFICE,NaN,NaN,6,HARRIS
3,TX101015A,DISTRICT ATTORNEYS OFFICE HOUSTON,DISTRICT ATTORNEY'S,OFFICE,NaN,6,HARRIS
4,TX101015Y,HEALTH AND HUMAN SERV COMM OIG,HEALTH & HUMAN SERV COMMISSION,OFFICE OF INSPECTOR GENERAL,HOUSTON,6,HARRIS

In [4]:
weather_data_path = "csv_data/HOU_daily.csv"

In [5]:
weather_data_df = pd.read_csv(weather_data_path)
weather_data_df.head()

,Site4,Year,Max Temp,Min Temp,Avg Temp,HDDs,CDDs,Precipitation Water Equiv,Snowfall,Snow/Ice Depth,Full Date
0,HOU,1964,62,28,45.0,20.0,0.0,0.00,0.0,0.0,1/1/64
1,HOU,1964,70,36,53.0,12.0,0.0,0.00,0.0,0.0,1/2/64
2,HOU,1964,72,44,58.0,7.0,0.0,0.06,0.0,0.0,1/3/64
3,HOU,1964,61,50,55.5,9.5,0.0,0.00,0.0,0.0,1/4/64
4,HOU,1964,55,43,49.0,16.0,0.0,0.09,0.0,0.0,1/5/64

In [6]:
income_csv = "csv_data/income.csv"
income_df = pd.read_csv(income_csv)
income_df.head()

   year  median_household_income
0  1997                    39037
1  1998                    40690
2  1999                    41466
3  2000                    41220
4  2001                    43279

In [ ]:
# for index, row in ORI_df.iterrows():
#     print(row[0], ' County: ', row[6])

In [ ]:
# for row in test:
#     print(test.iloc[row,0])

In [ ]:

#  Only grabbing these items from the CDE API

# these are the crime stat lists.
ORI_list = []
year_list = [1997,1998,1999,2000,2001,2002,2003,
             2004,2005,2006,2007,2008,2009,2010,
             2011,2012,2013,2014,2015,2016,2017]
crime_list = ["aggravated-assault","homicide","rape","robbery","violent-crime"]

agg_assult_actual = []
agg_assult_cleared = []
homicide_actual = []
homicide_cleared = []
rape_actual = []
rape_cleared = []
robbery_actual = []
robbery_cleared = []
vc_actual = []
vc_cleared = []

#national lists
N_vc = []
N_population = []

# these will be used for the totals on the crime dataframe.  
# They are all in a series. 
# We are setting them to 0 so they can be added to. 
agg_assult_actual_cnt = 0
agg_assult_cleared_cnt = 0
homicide_actual_cnt = 0
homicide_cleared_cnt = 0
rape_actual_cnt = 0
rape_cleared_cnt = 0
robbery_actual_cnt = 0
robbery_cleared_cnt = 0
vc_actual_cnt = 0
vc_cleared_cnt = 0

# pause_counter = 0
# df = ORI_df

In [ ]:
# This function finds the average for a missing year.  
# If the loop comes across a missing year in the API, 
# it grabs the data for the prior year and the data for the next year and returns and average. 
# But if the API is missing a block of 3 or more years in a row, it will just 0 out that data. 
# You'll be able to see the agency and how much data it is missing below when you run the script. 

def missing_data(crime_var,key_api):
    
    if apidx != 0 and apidx-1 != 0:
        crime_var.append((crime_data["results"][apidx][key_api] + crime_data["results"][apidx-1][key_api])/2)
#         print(apidx)
#         print(crime_data["results"][apidx][key_api])
#         print(apidx-1)
#         print(crime_data["results"][apidx-1][key_api])
#         print(crime_var)
    else: 
        crime_var.append(0)
        print(crime_var)

In [ ]:
ORI_list = ORI_df[0].to_list()

In [ ]:
#URL call for estimated national violent crime data using a public API key.
national_url = "https://api.usa.gov/crime/fbi/sapi/api/estimates/national/1997/2017?API_KEY=lAhbHilA6cmNxP2IHrRlsSVZvFETZf4iczTN20GI"
national_crime_data = requests.get(national_url).json()

 #gather national data
nidx = 0    
for x in year_list:
    N_vc.append(national_crime_data["results"][nidx]["violent_crime"])
    N_population.append(national_crime_data["results"][nidx]["population"])
#     N_agg_assult.append(national_crime_data["results"][nidx]["aggravated_assault"])
#     N_off_fam.append(national_crime_data["results"][nidx]["offense_family"])
#     N_rape.append(national_crime_data["results"][nidx]["rape"])
#     N_simp_assult.append(national_crime_data["results"][nidx]["simple_assault"])
#     N_robbery.append(national_crime_data["results"][nidx]["robbery"])
#     N_manslaut.append(national_crime_data["results"][nidx]["manslaughter"])
#     N_murder.append(national_crime_data["results"][nidx]["murder"])
    nidx+=1

In [ ]:
national_crime_cnt_df = pd.DataFrame({"Year":year_list,
                             "Violent Crime":N_vc,
                             "Population":N_population
                             
                            }) 

# national_crime_cnt_df["Total"] = national_crime_cnt_df.iloc[:, 1:8].sum(axis = 1)
# national_crime_cnt_df["US Defined Total"] = national_crime_cnt_df.iloc[:,1:5].sum(axis = 1)
national_crime_cnt_df

    Year  Violent Crime  Population
0   1997        1636099   267783607
1   1998        1533887   270248003
2   1999        1426044   272690813
3   2000        1425486   281421906
4   2001        1439480   285317559
5   2002        1423677   287973924
6   2003        1383676   290788976
7   2004        1360088   293656842
8   2005        1390745   296507061
9   2006        1435123   299398484
10  2007        1422970   301621157
11  2008        1394461   304059724
12  2009        1325896   307006550
13  2010        1251248   309330219
14  2011        1206031   311587816
15  2012        1217057   313873685
16  2013        1168298   316497531
17  2014        1153022   318907401
18  2015        1285606   323405935
19  2016        1283220   325719178
20  2017        1199310   320896618

In [ ]:
# Because we are loopign through a dataframe (ORI_df), we need to use an iterrows loop.
# A basic for loop makes it count by columns instead of by rows. 
# https://cmdlinetips.com/2018/12/how-to-loop-through-pandas-rows-or-how-to-iterate-over-pandas-rows/
ORIdx = 0

for ORI_name in ORI_list:
    
    cridx = 0
    for crime in crime_list:
        
# URL calls using a public API Key (iiHnOKfno2Mgkt5AynpvPpUQTEyxE77jo1RU8PIv).   
        crime_url = "https://api.usa.gov/crime/fbi/sapi/api/summarized/agencies/"
        query_url = f"{crime_url}{ORI_list[ORIdx]}/{crime_list[cridx]}/1997/2017?API_KEY=lAhbHilA6cmNxP2IHrRlsSVZvFETZf4iczTN20GI"

        crime_data = requests.get(query_url).json()

        # Counters
        apidx = 0       #APi InDeX - this is for each dictionary in the API
        yridx = 0       #YeaR InDeX - this is for the contents of the year[list] up above.  It will be used to test if the year exists in the API.
        
#         print(ORI_list[ORIdx])# Just used for confirmation that the loop is working.  This may get commented out later. 
#         print(crime_list[cridx])
        
        # Try the section below unless you get a KeyError:
        # If we get a KeyError, it is because the page doesn't exist. Display the ORI as failed, and move on to the next one. 
        try:       

            # Loop through the APIs using the year_list[].  
            # First test to make sure the Year data exists.  
            # If it doesn't 0 out that part of the list. 
            for dates in year_list:

                # Next try testing to see if there year in year_list[] matches with the year in the API.  
                # If it does, then grab the data and append the lists. 
                # If it doesn't, run the missing data function to see we can get an average for the missing year. 
                # If we get an IndexError, it is because the API doesn't have as many years as year_list[] 
                # the API ended too soon and so the index doesn't match up with year_list[]
                # zero it out for that missing year and move on. 
                try:
                    if year_list[yridx] == crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "aggravated-assault":
                    
                        # print(crime_data["results"][apidx]["data_year"]) # This is just for testing.
                        agg_assult_actual.append(crime_data["results"][apidx]["actual"])
                        agg_assult_cleared.append(crime_data["results"][apidx]["cleared"])
                        apidx += 1
                        yridx += 1
                    
                    elif year_list[yridx] != crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "aggravated-assault":
                        missing_data(agg_assult_actual,"actual")
                        missing_data(agg_assult_cleared,"cleared")
                        yridx +=1
                        
                    elif year_list[yridx] == crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "homicide":
                        homicide_actual.append(crime_data["results"][apidx]["actual"])
                        homicide_cleared.append(crime_data["results"][apidx]["cleared"])
                        pidx += 1
                        yridx += 1
                    
                    elif year_list[yridx] != crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "homicide":
                        missing_data(homicide_actual,"actual")
                        missing_data(homicide_cleared,"cleared")
                        yridx +=1
                    
                    elif year_list[yridx] == crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "rape":
                        rape_actual.append(crime_data["results"][apidx]["actual"])
                        rape_cleared.append(crime_data["results"][apidx]["cleared"])
                        pidx += 1
                        yridx += 1
                        
                    elif year_list[yridx] != crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "rape":
                        missing_data(rape_actual,"actual")
                        missing_data(rape_cleared,"cleared")
                        yridx +=1

                    elif year_list[yridx] == crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "robbery":
                        robbery_actual.append(crime_data["results"][apidx]["actual"])
                        robbery_cleared.append(crime_data["results"][apidx]["cleared"])
                        pidx += 1
                        yridx += 1
                    
                    elif year_list[yridx] != crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "robbery":
                        missing_data(robbery_actual,"actual")
                        missing_data(robbery_cleared,"cleared")
                        yridx +=1
                        
                    elif year_list[yridx] == crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "violent-crime":
                        vc_actual.append(crime_data["results"][apidx]["actual"])
                        vc_cleared.append(crime_data["results"][apidx]["cleared"])
                        apidx += 1
                        yridx += 1
                    
                    elif year_list[yridx] != crime_data["results"][apidx]["data_year"] and crime_list[cridx] == "violent-crime":
                        missing_data(vc_actual,"actual")
                        missing_data(vc_cleared,"cleared")
                        yridx +=1

                    
                except IndexError:
                    if crime_list[cridx] == "aggravated-assault": 
                        agg_assult_actual.append(0)
                        agg_assult_cleared.append(0)
                    elif crime_list[cridx] == "homicide":
                        homicide_actual.append(0)
                        homicide_cleared.append(0)
                    elif crime_list[cridx] == "rape":
                        rape_actual.append(0)
                        rape_cleared.append(0)
                    elif crime_list[cridx] == "robbery":
                        robbery_actual.append(0)
                        robbery_cleared.append(0)
                    elif crime_list[cridx] == "violent-crime":
                        vc_actual.append(0)
                        vc_cleared.append(0)

            # turn the list into a series
            agg_assult_actual_sr = pd.Series(agg_assult_actual)

            # add the series contents into the count dataframe
            agg_assult_actual_cnt = agg_assult_actual_cnt + agg_assult_actual_sr
            round(agg_assult_actual_cnt)
            
            # empty out the list so it can be refilled when it loops to the next API. 
            del agg_assult_actual[:]

            agg_assult_cleared_sr = pd.Series(agg_assult_cleared)  
            agg_assult_cleared_cnt = agg_assult_cleared_cnt + agg_assult_cleared_sr
            round(agg_assult_cleared_cnt)
            del agg_assult_cleared[:]
            
            homicide_actual_sr = pd.Series(homicide_actual)  
            homicide_actual_cnt = homicide_actual_cnt + homicide_actual_sr
            round(homicide_actual_cnt)
            del homicide_actual[:]
            
            homicide_cleared_sr = pd.Series(homicide_cleared)  
            homicide_cleared_cnt = homicide_cleared_cnt + homicide_cleared_sr
            round(homicide_cleared_cnt)
            del homicide_cleared[:]

            rape_actual_sr = pd.Series(rape_actual)  
            rape_actual_cnt = rape_actual_cnt + rape_actual_sr
            round(rape_actual_cnt)
            del rape_actual[:]
            
            rape_cleared_sr = pd.Series(rape_cleared)  
            rape_cleared_cnt = rape_cleared_cnt + rape_cleared_sr
            round(rape_cleared_cnt)
            del rape_cleared[:]

            robbery_actual_sr = pd.Series(robbery_actual)  
            robbery_actual_cnt = robbery_actual_cnt + robbery_actual_sr
            round(robbery_actual_cnt)
            del robbery_actual[:]
            
            robbery_cleared_sr = pd.Series(robbery_cleared)  
            robbery_cleared_cnt = robbery_cleared_cnt + robbery_cleared_sr
            round(robbery_cleared_cnt)
            del robbery_cleared[:]

            vc_actual_sr = pd.Series(vc_actual)  
            vc_actual_cnt = vc_actual_cnt + vc_actual_sr
            round(vc_actual_cnt)
            del vc_actual[:]
            
            vc_cleared_sr = pd.Series(vc_cleared)  
            vc_cleared_cnt = vc_cleared_cnt + vc_cleared_sr
            round(vc_cleared_cnt)
            del vc_cleared[:]
            
        except KeyError:
            print(f"exception: {ORI_name} - No Data")
            ORIdx+=1
            
    cridx+=1
ORIdx+=1

print('Completed API calls')

In [ ]:
crime_cnt_df = pd.DataFrame({"Year":year_list,
                             "Aggravated Assault Actual":agg_assult_actual_cnt,
                             "Aggravated Assault Cleared":agg_assult_cleared_cnt,
                             "Homicide Actual":homicide_actual_cnt,
                             "Homicide Cleared":homicide_cleared_cnt,
                             "Rape Actual":rape_actual_cnt,
                             "Rape Cleared":rape_cleared_cnt,
                             "Robbery Actual":robbery_actual_cnt,
                             "Robbery Cleared":robbery_cleared_cnt,
                             "Violent Crime Actual":vc_actual_cnt,
                             "Violent Crime Cleared":vc_cleared_cnt
                             
                            }) 

# crime_cnt_df["Total"] = crime_cnt_df.iloc[:, 1:8].sum(axis = 1)


# US definition of violent crime is:  Aggravated and Simple Assault, Rape, and Robbery. 
# Murder and Manslaughter are counted seperately. 
# Human Trafficing, Animal Cruelty, etc. are in another catagory as well. 
# crime_cnt_df["US Defined Total"] = crime_cnt_df.iloc[:,1:5].sum(axis = 1)
crime_cnt_df["Estimated National Violent Crime Total"] = national_crime_cnt_df["Violent Crime"]

crime_cnt_df

In [ ]:
avg_temps=[]
min_temps=[]
max_temps=[]
weather_sum={}
#Initializing variables to hold calculated or filtered data for each year to be appended to lists
avg_temp=0
min_temp=0
max_temp=0
#variable to hold value of year
year=1997
#filter rows for each year using  the boolean expression
for year in range(1997,2018):
    new_df=weather_data_df[weather_data_df['Year']==year]
    avg_temp=new_df['Avg Temp'].mean()
    min_temp=new_df['Min Temp'].min()
    max_temp=new_df['Max Temp'].max()
    avg_temps.append(avg_temp)
    min_temps.append(min_temp)
    max_temps.append(max_temp)
    year+=1
print(avg_temps)
print(min_temps)
print(max_temps)

In [ ]:
avg_temps = [round(t,2) for t in avg_temps]
crime_cnt_df["Average Temperature"] = avg_temps
crime_cnt_df["Minimum Temperature"] = min_temps
crime_cnt_df["Maximum Temperature"] = max_temps

In [ ]:
crime_cnt_df["Household Median Income"] = income_df["median_household_income"]

In [ ]:
# crime_cnt_df["Year"].astype(str)
crime_cnt_df

In [ ]:
crime_cnt_df.to_csv(output_path, index=False)
national_crime_cnt_df.to_csv(national_output_path, index = False)

In [ ]:
crime_avg_temp_plt = plt.scatter(x=crime_cnt_df["Average Temperature"], 
                           y=crime_cnt_df["Violent Crime"], 
#                            s=crime_cnt_df["Total"]/10, 
                           color="red", 
                           edgecolor = "black") 
#                            alpha = .5, 
#                            label = "Crime Total")

plt.title("Violent Crime vs Average Temperature")
plt.xlabel("Average Temperature")
plt.ylabel("Violent Crime Rate in Harris County")
plt.grid()
plt.tight_layout()
plt.savefig("output_plot/crime_total_avg_temp.png", bbox_inches = "tight")
plt.show()

In [ ]:
x_axis = [1997, 1999, 2001, 2003, 2005, 2007, 2009, 2011, 2013, 2015, 2017]

plt.plot(crime_cnt_df["Year"], crime_cnt_df["Violent Crime"]) 

plt.xticks(x_axis)                                          
plt.title("Violent Crime per Year in Harris County")
plt.xlabel("Years")
plt.ylabel("Violent Crime Rate")
plt.grid()
plt.tight_layout()
plt.savefig("output_plot/crime_total_per_year.png", bbox_inches = "tight")
plt.show()

In [ ]:
plt.plot(crime_cnt_df["Year"], crime_cnt_df["Average Temperature"]) 

plt.xticks(x_axis)                                          
plt.title("Average Temperature per year")
plt.xlabel("Years")
plt.ylabel("Temperature")
plt.grid()
plt.tight_layout()
plt.savefig("output_plot/average_temp_per_year.png", bbox_inches = "tight")
plt.show()

In [ ]:
plt.plot(crime_cnt_df["Year"], crime_cnt_df["Minimum Temperature"], color = "skyblue")
plt.plot(crime_cnt_df["Year"], crime_cnt_df["Maximum Temperature"], color = "red")
plt.plot(crime_cnt_df["Year"], crime_cnt_df["Average Temperature"], color = "orange")
plt.legend()
plt.xticks(x_axis)                                          
plt.title("Max and Min Temperature per year")
plt.xlabel("Years")
plt.ylabel("Temperature")
plt.grid()
plt.tight_layout()
plt.savefig("output_plot/max_and_min_temp_per_year.png", bbox_inches = "tight")
plt.show()

In [ ]:
fig, ax1 = plt.subplots()

ax1.set_xlabel('Years')
ax1.set_ylabel('Crime Rate')
ax1.plot(crime_cnt_df["Year"], crime_cnt_df["Violent Crime"], color="red")
ax1.tick_params(axis='y', labelcolor="red")

ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis


ax2.set_ylabel('Median Household Income')  # we already handled the x-label with ax1
ax2.plot(crime_cnt_df["Year"], crime_cnt_df["Household Median Income"], color="blue")
ax2.tick_params(axis='y', labelcolor="blue")


plt.xticks(x_axis)                                          
plt.title("Household Median Income and Violent Crime Rate in Harris County")
plt.grid()
plt.tight_layout()
plt.savefig("output_plot/income_vs_crime_per_year.png", bbox_inches = "tight")
plt.show()

In [ ]:
crime_vs_income_plt = plt.scatter(x=crime_cnt_df["Household Median Income"], 
                                  y=crime_cnt_df["Violent Crime"], 
                                  color="red", 
                                  edgecolor = "black") 

plt.title("Violent Crime Totals vs Income")
plt.xlabel("Household Median Income in Dollars")
plt.ylabel("Total Crime Rate")
plt.grid()
plt.tight_layout()
plt.savefig("output_plot/crime_vs_income.png", bbox_inches = "tight")
plt.show()

In [ ]:
# crime_bubble = plt.scatter(x=crime_cnt_df["Household Median Income"], 
#                            y=crime_cnt_df["Average Temperature"], 
#                            s=crime_cnt_df["Total"]*.1, 
#                            color="red", 
#                            edgecolor = "black", 
#                            alpha = .5)

# plt.title("Crime vs Temperature vs Median Household Income")
# plt.xlabel("Household Median Income in Dollars")
# plt.ylabel("Average Temperature")
# plt.grid()
# plt.tight_layout()
# plt.savefig("output_plot/crime_vs_temp_vs_income.png", bbox_inches = "tight")
# plt.show()